### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [sammarks/objection-graphql-relay#9]
This npm package needs a TypeScript types declaration file so that developers who enjoy writing with TS can use it with this package and have a better development experience. Would you like me to write one?

**Comment by sammarks** [comment]
I've actually been meaning to do this for a little bit now since the rest of the stuff I'm working on is in TypeScript. Whenever I have some free time I'll work on it, but I'm always open to PRs!

**Comment by geopic** [comment]
Will get started on it soon then @sammarks , thanks

**Comment by geopic** [comment]
Sorry for the delay, I've been busy this month. Would you still like me to do this or have you already started on it?

**Comment by sammarks** [comment]
Go for it!

**Comment by geopic** [comment]
I'll get started on it then :smile:
